### ISSUE TITLE
Nose helper only works on all files?

### ISSUE THREAD

**Issue by ionelmc** [thomasw/testtube#8]
Any explanation as to why? Couldn't find any in the code comments.

**Comment by thomasw** [comment]
First, let me clarify that that all files configuration option refers to whether or not the test is applied to the specific file that changed or if it is run against the entire repo. In nose's case, you can't simply pass in a changed file and have it only run the tests relating to that file out of the box, so it is set to always behave as an all files helper.

I'm assuming you're asking because you'd like to only run the tests that could be impacted when a specific file changes? If that's the case, you should use an incremental test runner nose plugin like https://github.com/jbochi/bazinga (I haven't used this particular plugin and I seem to recall there being one that was a bit more active, but I can't find it at the moment). It the code paths that a test uses when it is run, stores that information, and then when that code changes it only runs the tests where there is a codepath overlap. If you find a more actively developed plugin that is similar to this, please post it. I'll keep looking as well so that the best option can be recommended from the docs.

If you were to use such a plugin as the one I linked, then the nose helper would still be an all files helper. It'd manage what tests it needs to run on its own.

Another interpretation of your question just occurred to me: If you're changing specific test files, you may want nose to only run the tests in those files instead of your entire suite. I hadn't considered that particular use case. Is that what you mean?

**Comment by ionelmc** [comment]
Ooops, I assumed it only watches test files.

**Comment by thomasw** [comment]
Ah, it'll run `nosetests` whenever a file matching the specified regex changes. So, one could configure it that way, but the way I have used it (and the way I have typically seen others use it) is to configure it so that it runs whenever any python file changes.
